/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fakedatingsim;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import static java.lang.Math.pow;
import static java.lang.Math.sqrt;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Rais
 */
public class FindUser extends javax.swing.JFrame {
    
    private FriendZoneUser user;
    private boolean male = false, female = false;
    private HashMap<String,double[]> coord = new <String,double[]>HashMap();//Coordinate of Locatios
    private HashMap<ArrayList<String>,FriendZoneUser> list = new <ArrayList<String>,FriendZoneUser>HashMap();//Connect interest to which user
    private ArrayList<FriendZoneUser> database;
    private DefaultListModel listModel = new DefaultListModel();
    private ArrayList<ArrayList<String>> otherInt = new <ArrayList<String>>ArrayList();//ArrayList of interest, for before and also after sorted
    private ArrayList<FriendZoneUser> finalList = new <FriendZoneUser>ArrayList();//List of users that user wants to chat with
    private ArrayList<FriendZoneUser> initialList = new <FriendZoneUser>ArrayList();//Initial list of users within range
    private String opSentence;

    /**
     * Creates new form FindUser
     */
    public FindUser(FriendZoneUser user, ArrayList<FriendZoneUser> database, ArrayList<FriendZoneUser> finalList) {
        initComponents();
        getContentPane().setBackground(Color.PINK);
        errorLabel.setVisible(false);
        this.botList.setModel(listModel);
        this.user = user;
        this.database = database;
        this.finalList = finalList;
        setHash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        botList = new javax.swing.JList<>();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rangeText = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botList.setModel(listModel);
        jScrollPane1.setViewportView(botList);

        maleRadio.setText("Male");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });

        femaleRadio.setText("Female");
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Ctrl + Left Click to Multi Select");

        rangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangeTextActionPerformed(evt);
            }
        });

        errorLabel.setBackground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Please enter an integer");

        jLabel2.setText("Enter a max range e.g. 3000");

        jLabel3.setText("Choose your orientation,... or swing both ways");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(errorLabel))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maleRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(saveButton)
                    .addComponent(jLabel1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        male = !male;
    }//GEN-LAST:event_maleRadioActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        female = !female;
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        boolean numeric = true;
        try {
            Double num = Double.parseDouble(rangeText.getText());
        } catch (NumberFormatException e) {
            numeric = false;
        }
        if(numeric){
            errorLabel.setVisible(false);
            listModel.clear();
            listModel.removeAllElements();
            String sentence;
            FriendZoneUser temp;
            getList();
            sortList(user.getInterest(),otherInt);
            ListRepresentation whichRange = new ListRepresentation(opSentence,null);
            listModel.addElement(whichRange);
            for(int i = 0; i < otherInt.size(); i++){
                temp = list.get(otherInt.get(i));
                sentence = temp.getFirstName() + " " + temp.getLastName() + ", " + temp.getAge() + " " + temp.getGender() + ", lives in " + temp.getCity() + ", compatability is " + otherInt.get(i).get(5);
                listModel.addElement(new ListRepresentation(sentence, temp));
            } 
        }
        else{
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ArrayList<ListRepresentation> a = new <ListRepresentation>ArrayList(botList.getSelectedValuesList());
        for(int i = 0; i < a.size(); i++){
            if(!finalList.contains(a.get(i).getUser()))
                finalList.add(a.get(i).getUser());
        }
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void rangeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangeTextActionPerformed

    public void getList(){
        otherInt.clear();
        initialList.clear();    
        list.clear();
        Search imp = new Search(database, user, Double.parseDouble((String)rangeText.getText()),male,female);
        initialList = imp.increaseRad();
        opSentence = imp.getOpSent();
        for(int i = 0; i < initialList.size(); i++)
            otherInt.add(initialList.get(i).getInterest()); 
    }
    
     public Double radEq(Double x, Double h, Double y, Double k){

        Double rad;

        rad = sqrt((pow(x-h, 2) + pow(y-k, 2)));

        return rad;
    }
    
     public ArrayList<ArrayList<String>> sortList(ArrayList<String> realUser, ArrayList<ArrayList<String>> dummyUser){
         for(int i = 0; i < dummyUser.size(); i ++)
        {
            int counter = 0;
            for(int j = 0; j < dummyUser.get(i).size(); j ++)
            {
                for(int k = 0; k < realUser.size(); k++)
                {
                    if(dummyUser.get(i).get(j).equals(realUser.get(k)))
                    {
                        counter++;
                    }
                }
                
            }
            dummyUser.get(i).add(Integer.toString(counter));
            list.put(dummyUser.get(i), initialList.get(i));
        }
        SortInterest sort = new SortInterest(2, dummyUser);//Create new SortInterest class
        dummyUser = sort.selectionSort();//Sort the ArrayList and is returned
        return dummyUser; 
     }
     
    public void setHash(){
        String line;
        try{
            BufferedReader br = new BufferedReader(new FileReader("locations.txt"));
            while((line = br.readLine()) != null){
                String[] a = line.split(",");
                String[] b = a[1].split("!");
                double x = Double.parseDouble(b[0]), y = Double.parseDouble(b[1]);
                double[] loc = {x,y};
                coord.put(a[0], loc);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FindUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FindUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FindUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<ListRepresentation> botList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField rangeText;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
